### ISSUE TITLE
This variable is empty assigned?

### ISSUE THREAD

**Issue by boudewijnbout** [DaanKorver/connect-your-tribe-fdnd-squad-page#8]
https://github.com/DaanKorver/connect-your-tribe-fdnd-squad-page/blob/d7c830fd6e6513ef6216463cc44e0c94670677af/scripts/index.js#L7

**Comment by DaanKorver** [comment]
@boudewijnbout 
Ready for review.

Branch: hotfix/shuffle-code-cleanup

**Comment by boudewijnbout** [comment]
Good fix.
